# Application Configuration
spring.application.name=Savory

# Database Configuration
# MySql Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/savorydb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Security Configuration

# JWT Configuration

# Logging Configuration
logging.level.org.springframework.security=DEBUG
#logging.level.com.fasterxml.jackson=DEBUG
#logging.level.org.springframework.web=DEBUG

# Api Documentation
#springdoc.api-docs.path=/api-docs