# Application Configuration
spring.application.name=Savory

# Graphql Configuration
spring.graphql.graphiql.enabled=true

# Database Configuration
# MongoDB Database configuration
spring.data.mongodb.uri=mongodb://localhost:27017/savorydb
#spring.data.mongodb.uri=mongodb://143.47.189.76:27017/savorydb

# MySql Database configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/savoryauthdb
#spring.datasource.url=jdbc:mysql://143.47.189.76:3306/savoryauthdb
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=admin
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true

# Security Configuration

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate= DEBUG