services:
  mongodb:
    image: mongo:8
    container_name: savory-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin #TODO: Enable auth and use a strong password
#      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - savory-net
    volumes:
      - savorydb-data:/data/db

#  mysqldb:
#    image: mysql:latest #TODO: Use fixed version instead of "latest"
#    container_name: savory-auth-db
#    restart: unless-stopped
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: savoryauthdb
#      MYSQL_USER: admin #TODO: Enable auth and use a strong password
#      MYSQL_PASSWORD: root
#    networks:
#      - savory-net
#    volumes:
#      - savory-auth-data:/var/lib/mysql

  mongo-express:
    image: mongo-express:latest #TODO: Use fixed version instead of "latest"
    container_name: savory-mongo-ui
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin #TODO: Use a strong password
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - savory-net

#  savory-backend:
#    image: devyourid/savory-backend:latest
#    container_name: savory-backend
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    networks:
#      - savory-net
    # depends_on:
    #   - mongodb
    #   - mysqldb

volumes:
  savorydb-data:
  savory-auth-data:

networks:
  savory-net:
    driver: bridge